### ISSUE TITLE
Video processing

### ISSUE THREAD

**Issue by superdev812** [alexiscn/MTTransitions#1]
Hello,

I'd like to merge two videos using these transitions. There is only MTIImage and I can't use the transitions for video processing.
Please let me know how to implement the video transitions.

Thank you.

**Comment by alexiscn** [comment]
I am working on it now. :D

**Comment by alexiscn** [comment]
Please referer `VideoTransitionSampleViewController` for details.

I am not fully test all the video transition yet. But the demo seems to be worked.

There are some limits:

* The size of two videos must be the same
* The tow videos must contains video track and audio track
