### ISSUE TITLE
MTIImageView set background color

### ISSUE THREAD

**Issue by hiren6994** [alexiscn/MTTransitions#10]
Hello Sir,
I try to set background color to MTIImageView but it alsways show black color behind imageview, so please help me,

**Comment by hiren6994** [comment]
Dear team, Awaiting your reply.

**Comment by kazi-nayeem** [comment]
```
MTIImageView.clearColor = MTLClearColorMake(1.0,0.0,0.0,1.0); // Color you want to set
```

**Comment by hiren6994** [comment]
thanks for your reply, it works for me, thank you very much
