### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by devindoty** [alexiscn/MTTransitions#12]
`Incorrect argument label in call (have 'cgImage:isOpaque:', expected '__cgImage:isOpaque:')`
`Replace 'cgImage' with '__cgImage'`

**Comment by alexiscn** [comment]
Works fine in with:
Xcode Version 12.4 
iOS version 14.4.2.

What's your Xcode version?

**Comment by devindoty** [comment]
Weird same, Version 12.4 (12D4e)

Any idea what could be causing it? I'm using cocoa pods with the latest version in a mix objc / swift app

**Comment by alexiscn** [comment]
Can you provide a minimum project that can not complied

**Comment by devindoty** [comment]
[MTTransitionsDemo.zip](https://github.com/alexiscn/MTTransitions/files/6279815/MTTransitionsDemo.zip)

**Comment by alexiscn** [comment]
Try with 1.6.3.

**Comment by devindoty** [comment]
it works, thank you!!
