### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by R3l0ad3d** [alexiscn/MTTransitions#28]
Please add Swift Package Manager it this project. Every one moving SPM .

**Comment by alexiscn** [comment]
add in [1139068](https://github.com/alexiscn/MTTransitions/commit/1139068bdb772d7b242bea5d40e7a6d95a20e32a), please check if it works, thanks.

**Comment by R3l0ad3d** [comment]
Thank you very much for this. But i think there is a problem. its only work if i select master branch.
![Screenshot 2022-08-27 at 1 01 40 PM](https://user-images.githubusercontent.com/9822948/187019122-f5d7fed3-f10e-4f0c-8c0d-b3714d109e52.png)
if i select like this image this error show

**Comment by R3l0ad3d** [comment]
Sorry, there is another problem. no transition work . please check this also.

**Comment by alexiscn** [comment]
> Thank you very much for this. But i think there is a problem. its only work if i select master branch. ![Screenshot 2022-08-27 at 1 01 40 PM](https://user-images.githubusercontent.com/9822948/187019122-f5d7fed3-f10e-4f0c-8c0d-b3714d109e52.png) if i select like this image this error show

fixed in tag 1.6.6
