### ISSUE TITLE
你好,你的demo转场是黑的 貌似有bug了

### ISSUE THREAD

**Issue by CoderDeYu** [alexiscn/MTTransitions#7]
我用的是xcode11.5的模拟器

**Comment by alexiscn** [comment]
Can you try the demo in your device ?

**Comment by alexiscn** [comment]
I tried with my emulator of iPhone 11 , which works fine.

Alos Xcode 11.5.

Which demo the transition is black?

**Comment by CoderDeYu** [comment]
全部转成都是黑的
我用的模拟器

**Comment by CoderDeYu** [comment]
我使用真机,结果是正常运行的

**Comment by alexiscn** [comment]
Some transition seems not to be working on the enumlator. But most of them works fine.

![image](https://user-images.githubusercontent.com/1132546/87114023-22a5c080-c2a2-11ea-8f9a-e0a79ba5937a.png)

**Comment by alexiscn** [comment]
Some transition may not working on the emulator. But most of them works fine.

![image](https://user-images.githubusercontent.com/1132546/87114107-55e84f80-c2a2-11ea-8dbb-3664697e8a1f.png)

**Comment by CoderDeYu** [comment]
不是 模拟器是全部都不行 真机就全部可以哈

**Comment by CoderDeYu** [comment]
图片是可以的  但是视频不行
