### ISSUE TITLE
Create Video From Images with transition

### ISSUE THREAD

**Issue by hiren6994** [alexiscn/MTTransitions#9]
i run your code but this is not working for Create Video From Images with transition, it just blinking only one image, i try to fix it but not getting done by me, so i request you to provide this solution. please look 'MTMovieMaker' class, thanks,

**Comment by alexiscn** [comment]
Are you running the demo using Simulator ?

Currently the demo can only run in the real device.

**Comment by hiren6994** [comment]
yes, it running on simulator, can it works in device?

**Comment by alexiscn** [comment]
> yes, it running on simulator, can it works in device?

Yes. It works in iPhone device.

**Comment by hiren6994** [comment]
ok thanks for quick help, i try in device and let you know ones it done
